.TH "nginx" "1" "" "" ""
.SH "NAME"
nginx \- small, but very powerful and efficient web server
.br 

.br 
.SH "SYNOPSIS"
\fBnginx\fR [options] <configuration file>
.br 

.br 
.SH "DESCRIPTION"
\fBnginx\fR is a server that can be used as standalone HTTP server and as 
a reverse proxy server before some Apache or another big server to reduce 
load to backend servers by many concurrent HTTP\-sessions.
.br 

.br 
.SH "OPTIONS"
A summary of options is included below:
.br 

.br 
\fB\-c\fR <configuration file>
Specifies a particular configuration file for nginx to load.
.br 
\fB\-v\fR
Show version of program.
.br 
\fB\-t\fR
Tests nginx configuration
.br 
.br 

.br 
You can find further information about this webserver in http://nginx.net/docs_en.txt.
.br 

.br 
.SH "AUTHORS"
\fBnginx\fR was written by Igor Sysoev.
.br 

.br 
This manual page was written by Jose Parrella <joseparrella@cantv.net>,
for the Debian project (but may be used by others).

